
FROM node:20-alpine

WORKDIR /app

# install server deps 
COPY server/package*.json ./server/
RUN npm install --prefix server

# install client deps
COPY client/package*.json ./client/
RUN npm install --prefix client

# copy full project
COPY . .

# build client
RUN npm run build --prefix client

# move build to server
RUN mkdir -p server/public && cp -r client/dist/* server/public/
 
EXPOSE 5000

CMD ["npm", "start", "--prefix", "server"]


# create a .dockerignore file:
# vim .dockerignore
# node_modules
# client/node_modules
# server/node_modules
# */node_modules
